/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressBook: typeof import('./components/addressBook/addressBook.vue')['default']
    CmImage: typeof import('./components/cmImage/cmImage.vue')['default']
    Empty: typeof import('./components/empty/empty.vue')['default']
    GoodsCard: typeof import('./components/goodsCard/goodsCard.vue')['default']
    GoTop: typeof import('./components/goTop/goTop.vue')['default']
    JumpPage: typeof import('./components/jumpPage/jumpPage.vue')['default']
    Loading1: typeof import('./components/qiun-loading/loading1.vue')['default']
    Loading2: typeof import('./components/qiun-loading/loading2.vue')['default']
    Loading3: typeof import('./components/qiun-loading/loading3.vue')['default']
    Loading4: typeof import('./components/qiun-loading/loading4.vue')['default']
    Loading5: typeof import('./components/qiun-loading/loading5.vue')['default']
    MpHtml: typeof import('./components/mp-html/mp-html.vue')['default']
    MyTabContent: typeof import('./components/myTabs/myTabContent.vue')['default']
    MyTabs: typeof import('./components/myTabs/myTabs.vue')['default']
    Node: typeof import('./components/mp-html/node/node.vue')['default']
    OrderDetail: typeof import('./components/orderDetail/orderDetail.vue')['default']
    PopupPicker: typeof import('./components/popupPicker/popupPicker.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    QiunDataCharts: typeof import('./components/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunError: typeof import('./components/qiun-error/qiun-error.vue')['default']
    QiunLoading: typeof import('./components/qiun-loading/qiun-loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAddress: typeof import('./components/selectAddress/selectAddress.vue')['default']
    Service: typeof import('./components/service/service.vue')['default']
    Swiper: typeof import('./components/swiper/swiper.vue')['default']
    Tabbar: typeof import('./components/tabbar/tabbar.vue')['default']
    VersionUpdate: typeof import('./components/versionUpdate/versionUpdate.vue')['default']
  }
}
